Experiment No: 2

Title: Matrix Operations

Aim: Write a python program to perform matrix operations

In [8]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[10,20,30],[40,50,60],[70,80,90]])

addition = A + B

subtraction = A - B

multiplication = A @ B

print("Additon : \n",addition)
print("\n")

print("Subtraction : \n",subtraction)
print("\n")

print("Multiplication : \n",multiplication)
print("\n")


Additon : 
 [[11 22 33]
 [44 55 66]
 [77 88 99]]


Subtraction : 
 [[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]


Multiplication : 
 [[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


